"""create chat_line table

Revision ID: 98bc9b30fa36
Revises: 193f4a40074f
Create Date: 2024-10-24 06:34:35.659554

"""
import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import table

# revision identifiers, used by Alembic.
revision: str = '98bc9b30fa36'
down_revision: Union[str, None] = '193f4a40074f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

CHAT_LINE = table("chat_lines",
                  sa.Column('id', sa.Integer(), nullable=False),
                  sa.Column('user_id', sa.Uuid(), nullable=False),
                  sa.Column('chat_id', sa.Integer(), nullable=False),
                  sa.Column('line_text', sa.String(), nullable=False),
                  sa.Column('created_at', sa.DateTime(), nullable=False))

USER_ID = "ae7ee1ee-fade-4c11-afc0-53a702780211"
CHAT_ID = 0


def upgrade() -> None:
    op.bulk_insert(CHAT_LINE, [
        {
            "id": CHAT_ID,
            "user_id": USER_ID,
            "chat_id": "0",
            "line_text": "Test message generated by alimbic",
            "created_at": datetime.datetime.utcnow()
        }
    ])


def downgrade() -> None:
    op.execute(CHAT_LINE.delete().where(CHAT_LINE.c.id == CHAT_ID))
